/*
 * Exploration / fog of war (Manual Part-8). When GameOptions.exploration is on,
 * a realm only sees what it has explored: the land around its armies, revealed
 * as they travel, plus whatever it owns. We model the SCOUTED part — a per-realm
 * set of tile keys that only ever grows (the manual: once explored, the map
 * stays revealed). The "you always see your own counties" half is applied by
 * the client when it draws the fog, so it needs no per-turn bookkeeping here.
 *
 * Reveal is geometric (a hex disk around a position), so it needs no tile map —
 * extra keys for tiles that don't exist are harmless, since only real tiles are
 * ever drawn. Vision is monotonic, so there is no per-turn line-of-sight pass.
 */

import { EXPLORATION } from '../constants.ts';
import { offsetToCube, cubeToOffset } from '../maps/hex.ts';
import type { ExplorationState } from '../types/realm.ts';
import type { GameState } from '../types/realm.ts';

/** A fresh, empty exploration record (no realm has scouted anything). */
export function emptyExploration(): ExplorationState {
  return {};
}

/** Tolerate states built before exploration existed (old saves / fixtures). */
export function ensureExploration(state: GameState): ExplorationState {
  if (!state.exploration) state.exploration = emptyExploration();
  return state.exploration;
}

/** Canonical tile key (matches the renderer's `${col},${row}`). */
export function tileKey(col: number, row: number): string {
  return `${col},${row}`;
}

/** Has `realmId` explored the tile at (col,row)? */
export function isExplored(state: GameState, realmId: string, col: number, row: number): boolean {
  return ensureExploration(state)[realmId]?.[tileKey(col, row)] === true;
}

/** Mark a single tile explored for a realm. */
export function revealTile(state: GameState, realmId: string, col: number, row: number): void {
  const ex = ensureExploration(state);
  (ex[realmId] ??= {})[tileKey(col, row)] = true;
}

/**
 * Reveal every tile within `radius` hexes of (col,row) for `realmId` — the
 * vision an army casts over the land around it. Generated by walking the hex
 * disk in cube coordinates (no tile map needed).
 */
export function revealDisk(
  state: GameState,
  realmId: string,
  col: number,
  row: number,
  radius: number = EXPLORATION.visionRadius,
): void {
  const centre = offsetToCube({ col, row });
  for (let dx = -radius; dx <= radius; dx += 1) {
    for (let dy = Math.max(-radius, -dx - radius); dy <= Math.min(radius, -dx + radius); dy += 1) {
      const dz = -dx - dy;
      const o = cubeToOffset({ x: centre.x + dx, y: centre.y + dy, z: centre.z + dz });
      revealTile(state, realmId, o.col, o.row);
    }
  }
}

/** Reveal the ground an army covers on a march: a disk around each tile of the
 *  path segment it actually traversed (so scouting follows the whole route). */
export function revealAlong(
  state: GameState,
  realmId: string,
  tiles: { col: number; row: number }[],
): void {
  for (const t of tiles) revealDisk(state, realmId, t.col, t.row);
}
